// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.5
// source: employee.proto

package employeepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmployeeServiceClient is the client API for EmployeeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmployeeServiceClient interface {
	GetEmployeeList(ctx context.Context, in *GetEmployeeListRequest, opts ...grpc.CallOption) (EmployeeService_GetEmployeeListClient, error)
}

type employeeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeServiceClient(cc grpc.ClientConnInterface) EmployeeServiceClient {
	return &employeeServiceClient{cc}
}

func (c *employeeServiceClient) GetEmployeeList(ctx context.Context, in *GetEmployeeListRequest, opts ...grpc.CallOption) (EmployeeService_GetEmployeeListClient, error) {
	stream, err := c.cc.NewStream(ctx, &EmployeeService_ServiceDesc.Streams[0], "/employee.EmployeeService/GetEmployeeList", opts...)
	if err != nil {
		return nil, err
	}
	x := &employeeServiceGetEmployeeListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EmployeeService_GetEmployeeListClient interface {
	Recv() (*GetEmployeeListResponse, error)
	grpc.ClientStream
}

type employeeServiceGetEmployeeListClient struct {
	grpc.ClientStream
}

func (x *employeeServiceGetEmployeeListClient) Recv() (*GetEmployeeListResponse, error) {
	m := new(GetEmployeeListResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EmployeeServiceServer is the server API for EmployeeService service.
// All implementations must embed UnimplementedEmployeeServiceServer
// for forward compatibility
type EmployeeServiceServer interface {
	GetEmployeeList(*GetEmployeeListRequest, EmployeeService_GetEmployeeListServer) error
	mustEmbedUnimplementedEmployeeServiceServer()
}

// UnimplementedEmployeeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmployeeServiceServer struct {
}

func (UnimplementedEmployeeServiceServer) GetEmployeeList(*GetEmployeeListRequest, EmployeeService_GetEmployeeListServer) error {
	return status.Errorf(codes.Unimplemented, "method GetEmployeeList not implemented")
}
func (UnimplementedEmployeeServiceServer) mustEmbedUnimplementedEmployeeServiceServer() {}

// UnsafeEmployeeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployeeServiceServer will
// result in compilation errors.
type UnsafeEmployeeServiceServer interface {
	mustEmbedUnimplementedEmployeeServiceServer()
}

func RegisterEmployeeServiceServer(s grpc.ServiceRegistrar, srv EmployeeServiceServer) {
	s.RegisterService(&EmployeeService_ServiceDesc, srv)
}

func _EmployeeService_GetEmployeeList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetEmployeeListRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EmployeeServiceServer).GetEmployeeList(m, &employeeServiceGetEmployeeListServer{stream})
}

type EmployeeService_GetEmployeeListServer interface {
	Send(*GetEmployeeListResponse) error
	grpc.ServerStream
}

type employeeServiceGetEmployeeListServer struct {
	grpc.ServerStream
}

func (x *employeeServiceGetEmployeeListServer) Send(m *GetEmployeeListResponse) error {
	return x.ServerStream.SendMsg(m)
}

// EmployeeService_ServiceDesc is the grpc.ServiceDesc for EmployeeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmployeeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "employee.EmployeeService",
	HandlerType: (*EmployeeServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetEmployeeList",
			Handler:       _EmployeeService_GetEmployeeList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "employee.proto",
}
